// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vhthbnxzvuzrwilvorgy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZodGhibnh6dnV6cndpbHZvcmd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxOTE3MDUsImV4cCI6MjA3MDc2NzcwNX0.wsSAaPepbNfSh1zoWiTtdqdufmb6Hme6TmKKXU9MYnU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});